services:
  data:
    image: mariadb:latest
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: "testdb"
      MARIADB_USER: "app"
      MARIADB_PASSWORD: "app"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro
    networks:
      - tp3

  script:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    networks:
      - tp3

  http:
    image: nginx:latest
    ports:
      - "8081:80"    # on utilise 8081 au lieu de 8080
    volumes:
      - ./app:/app:ro
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - script
      - data
    networks:
      - tp3

networks:
  tp3:

volumes:
  db_data:
